In [1]:
import numpy as np
import pandas as pd 


In [2]:
df=pd.read_csv("mobile_prices.csv")

In [3]:
df.head(5)

Unnamed: 0                     Phone Name  RAM  ROM  Back Camera  \
0           0   POCO C50 (Royal Blue, 32 GB)    2   32            8   
1           1  POCO M4 5G (Cool Blue, 64 GB)    4   64           50   
2           2   POCO C51 (Royal Blue, 64 GB)    4   64            8   
3           3    POCO C55 (Cool Blue, 64 GB)    4   64           50   
4           4  POCO C51 (Power Black, 64 GB)    4   64            8   

   Front_Camera   Battery                                          Processor  \
0             5  5000 mAh  Mediatek Helio A22 Processor, Upto 2.0 GHz Pro...   
1             8  5000 mAh                   Mediatek Dimensity 700 Processor   
2             5  5000 mAh                                Helio G36 Processor   
3             5  5000 mAh                       Mediatek Helio G85 Processor   
4             5  5000 mAh                                Helio G36 Processor   

     Price  
0   ₹5,649  
1  ₹11,999  
2   ₹6,999  
3   ₹7,749  
4   ₹6,999

In [4]:
df.drop(columns=['Unnamed: 0'],inplace=True)
df.head(5)

Phone Name  RAM  ROM  Back Camera  Front_Camera  \
0   POCO C50 (Royal Blue, 32 GB)    2   32            8             5   
1  POCO M4 5G (Cool Blue, 64 GB)    4   64           50             8   
2   POCO C51 (Royal Blue, 64 GB)    4   64            8             5   
3    POCO C55 (Cool Blue, 64 GB)    4   64           50             5   
4  POCO C51 (Power Black, 64 GB)    4   64            8             5   

    Battery                                          Processor    Price  
0  5000 mAh  Mediatek Helio A22 Processor, Upto 2.0 GHz Pro...   ₹5,649  
1  5000 mAh                   Mediatek Dimensity 700 Processor  ₹11,999  
2  5000 mAh                                Helio G36 Processor   ₹6,999  
3  5000 mAh                       Mediatek Helio G85 Processor   ₹7,749  
4  5000 mAh                                Helio G36 Processor   ₹6,999

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2001 entries, 0 to 2000
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   Phone Name    2001 non-null   object
 1   RAM           2001 non-null   int64 
 2   ROM           2001 non-null   int64 
 3   Back Camera   2001 non-null   int64 
 4   Front_Camera  2001 non-null   int64 
 5   Battery       2001 non-null   object
 6   Processor     2001 non-null   object
 7   Price         2001 non-null   object
dtypes: int64(4), object(4)
memory usage: 125.2+ KB


In [6]:
df.duplicated().sum()

51

In [7]:
df.shape


(2001, 8)

In [8]:
df.drop_duplicates(inplace=True)

In [9]:
df.duplicated().sum()

0

In [10]:
df.isnull().sum()

Phone Name      0
RAM             0
ROM             0
Back Camera     0
Front_Camera    0
Battery         0
Processor       0
Price           0
dtype: int64

In [11]:
df.dropna(inplace=True)

In [12]:
df

Phone Name  RAM  ROM  Back Camera  \
0                      POCO C50 (Royal Blue, 32 GB)    2   32            8   
1                     POCO M4 5G (Cool Blue, 64 GB)    4   64           50   
2                      POCO C51 (Royal Blue, 64 GB)    4   64            8   
3                       POCO C55 (Cool Blue, 64 GB)    4   64           50   
4                     POCO C51 (Power Black, 64 GB)    4   64            8   
...                                             ...  ...  ...          ...   
1996              vivo T2x 5G (Marine Blue, 128 GB)    6  128           50   
1997  SAMSUNG Galaxy S23 5G (Phantom Black, 128 GB)    8  128           50   
1998            vivo X200 5G (Cosmos Black, 256 GB)   12  256           50   
1999             vivo Y28s 5G (Vintage Red, 128 GB)    6  128           50   
2000  SAMSUNG Galaxy S23 5G (Phantom Black, 256 GB)    8  256           50   

      Front_Camera                       Battery  \
0                5                      5000 mAh   
1                8                      5000 mAh   
2                5                      5000 mAh   
3                5                      5000 mAh   
4                5                      5000 mAh   
...            ...                           ...   
1996             8              5000 mAh Battery   
1997            12  3900 mAh Lithium Ion Battery   
1998            32              5800 mAh Battery   
1999             8              5000 mAh Battery   
2000            12  3900 mAh Lithium Ion Battery   

                                              Processor    Price  
0     Mediatek Helio A22 Processor, Upto 2.0 GHz Pro...   ₹5,649  
1                      Mediatek Dimensity 700 Processor  ₹11,999  
2                                   Helio G36 Processor   ₹6,999  
3                          Mediatek Helio G85 Processor   ₹7,749  
4                                   Helio G36 Processor   ₹6,999  
...                                                 ...      ...  
1996                  Mediatek Dimensity 6020 Processor  ₹12,999  
1997              Qualcomm Snapdragon 8 Gen 2 Processor  ₹39,999  
1998                           Dimensity 9400 Processor  ₹65,999  
1999                           Dimensity 6300 Processor  ₹14,499  
2000              Qualcomm Snapdragon 8 Gen 2 Processor  ₹42,999  

[1950 rows x 8 columns]

In [13]:
df.shape

(1950, 8)

In [14]:
df['Phone Name'].str.split()

0                     [POCO, C50, (Royal, Blue,, 32, GB)]
1                   [POCO, M4, 5G, (Cool, Blue,, 64, GB)]
2                     [POCO, C51, (Royal, Blue,, 64, GB)]
3                      [POCO, C55, (Cool, Blue,, 64, GB)]
4                    [POCO, C51, (Power, Black,, 64, GB)]
                              ...                        
1996            [vivo, T2x, 5G, (Marine, Blue,, 128, GB)]
1997    [SAMSUNG, Galaxy, S23, 5G, (Phantom, Black,, 1...
1998          [vivo, X200, 5G, (Cosmos, Black,, 256, GB)]
1999           [vivo, Y28s, 5G, (Vintage, Red,, 128, GB)]
2000    [SAMSUNG, Galaxy, S23, 5G, (Phantom, Black,, 2...
Name: Phone Name, Length: 1950, dtype: object

In [15]:
df.head(5)

Phone Name  RAM  ROM  Back Camera  Front_Camera  \
0   POCO C50 (Royal Blue, 32 GB)    2   32            8             5   
1  POCO M4 5G (Cool Blue, 64 GB)    4   64           50             8   
2   POCO C51 (Royal Blue, 64 GB)    4   64            8             5   
3    POCO C55 (Cool Blue, 64 GB)    4   64           50             5   
4  POCO C51 (Power Black, 64 GB)    4   64            8             5   

    Battery                                          Processor    Price  
0  5000 mAh  Mediatek Helio A22 Processor, Upto 2.0 GHz Pro...   ₹5,649  
1  5000 mAh                   Mediatek Dimensity 700 Processor  ₹11,999  
2  5000 mAh                                Helio G36 Processor   ₹6,999  
3  5000 mAh                       Mediatek Helio G85 Processor   ₹7,749  
4  5000 mAh                                Helio G36 Processor   ₹6,999

In [16]:
df['Price']=df['Price'].str.replace('₹','').str.replace(',','')

In [17]:
df['Price'] = pd.to_numeric(df['Price'], errors='coerce')
df = df.dropna(subset=['Price'])
df['Price'] = df['Price'].astype(int)
df.head(5)

C:\Users\Hi\AppData\Local\Temp\ipykernel_7592\3892478860.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Price'] = df['Price'].astype(int)


Phone Name  RAM  ROM  Back Camera  Front_Camera  \
0   POCO C50 (Royal Blue, 32 GB)    2   32            8             5   
1  POCO M4 5G (Cool Blue, 64 GB)    4   64           50             8   
2   POCO C51 (Royal Blue, 64 GB)    4   64            8             5   
3    POCO C55 (Cool Blue, 64 GB)    4   64           50             5   
4  POCO C51 (Power Black, 64 GB)    4   64            8             5   

    Battery                                          Processor  Price  
0  5000 mAh  Mediatek Helio A22 Processor, Upto 2.0 GHz Pro...   5649  
1  5000 mAh                   Mediatek Dimensity 700 Processor  11999  
2  5000 mAh                                Helio G36 Processor   6999  
3  5000 mAh                       Mediatek Helio G85 Processor   7749  
4  5000 mAh                                Helio G36 Processor   6999

In [18]:
df['Price'].unique()

array([  5649,  11999,   6999,   7749,   9249,  13999,   8999,   6499,
        15999,  10999,  23999,  17999,  14499,  17499,  21999,  29999,
        16499,  32999,  19499,  14999,   8499,  16999,  20999,  13689,
        27999,  24999,   9999,  11990,  19999,  15490,  39999,  18999,
        12999,  12990,  25999,  36999,  10499,   5999,  12499,  15499,
         7078,  15495,  12350,   8449,   7499,  10699,   9699,   7180,
        10489,   8949,  11499,   8049,   8749,  11998,  13499,   8427,
        11699,   8910,  11495,   5549,  12490,   9499,  11199,   9290,
        34999,  38999,  10790,   6049,  32299,  22999,  18499,  14490,
        13490,   8093,   7985,   2380,  49999,  30999,  40999,  29900,
        79999, 124999,  16200,  15899,  28999,  25990,  94999,   8199,
         9990,  36990,   9850,   7462,   7790,  50010,   7199,  41999,
       104999,  39930,  18450, 134999,  72999,  51990,  42999,  51490,
        62500,  27995,  27499,  17990,  16900,   8487,  19998,  29499,
      

In [19]:
df = df[(df['Price'] >= 7000) & (df['Price'] <= 50000)]
df['Price'] = df['Price'].astype('int64')

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1815 entries, 1 to 2000
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   Phone Name    1815 non-null   object
 1   RAM           1815 non-null   int64 
 2   ROM           1815 non-null   int64 
 3   Back Camera   1815 non-null   int64 
 4   Front_Camera  1815 non-null   int64 
 5   Battery       1815 non-null   object
 6   Processor     1815 non-null   object
 7   Price         1815 non-null   int64 
dtypes: int64(5), object(3)
memory usage: 127.6+ KB


In [21]:
df['RAM'].unique()

array([  4,   6,   8,  12,   3,   2, 512,   1,  16], dtype=int64)

In [22]:
df = df[~df['RAM'].isin([512, 16])]
df.reset_index(drop=True, inplace=True)
df['RAM'].unique()

array([ 4,  6,  8, 12,  3,  2,  1], dtype=int64)

In [23]:
df['Battery'] = df['Battery'].str.extract(r'(\d+)').astype(int)


In [24]:
df['Battery']=df['Battery'].astype(int)
df.head(5)

Phone Name  RAM  ROM  Back Camera  Front_Camera  \
0    POCO M4 5G (Cool Blue, 64 GB)    4   64           50             8   
1      POCO C55 (Cool Blue, 64 GB)    4   64           50             5   
2  POCO M4 5G (Power Black, 64 GB)    4   64           50             8   
3    POCO C55 (Power Black, 64 GB)    4   64           50             5   
4   POCO C55 (Forest Green, 64 GB)    4   64           50             5   

   Battery                         Processor  Price  
0     5000  Mediatek Dimensity 700 Processor  11999  
1     5000      Mediatek Helio G85 Processor   7749  
2     5000  Mediatek Dimensity 700 Processor  11999  
3     5000      Mediatek Helio G85 Processor   7749  
4     5000      Mediatek Helio G85 Processor   7749

In [25]:
df['ROM'].unique()

array([ 64, 128, 256,  32,  16,   8,   4, 512], dtype=int64)

In [26]:
df = df[~df['ROM'].isin([0])]
df.reset_index(drop=True, inplace=True)
df['ROM'].unique()

array([ 64, 128, 256,  32,  16,   8,   4, 512], dtype=int64)

In [27]:
df['Battery'].corr(df['Price'])

-0.1972875028941457

In [28]:
df['Front_Camera'].unique()

array([ 8,  5, 16, 13, 20, 32, 10, 25, 44, 50, 12, 24,  4,  2, 60,  1,  0],
      dtype=int64)

In [29]:
df = df[~df['Front_Camera'].isin([0,1,2])]
df.reset_index(drop=True, inplace=True)
df['Front_Camera'].unique()

array([ 8,  5, 16, 13, 20, 32, 10, 25, 44, 50, 12, 24,  4, 60],
      dtype=int64)

In [30]:
df['Back Camera'].unique()

array([ 50,  64,  48, 108,  13,  12,   8,  25,  16,  20, 200,  24,   2,
       100,  32], dtype=int64)

In [31]:
df['RAM'].corr(df['Price'])

0.6668412543711629

In [32]:
df['ROM'].corr(df['Price'])

0.584506429876787

In [33]:
df['Processor'] = df['Processor'].str.replace(r'\b(Mediatek|MediaTek)\b', 'MediaTek', regex=True)
df['Processor'].unique()

array(['MediaTek Dimensity 700 Processor', 'MediaTek Helio G85 Processor',
       'MediaTek Helio G99 Processor', 'MediaTek Helio G96 Processor',
       'Qualcomm Snapdragon 695 Processor',
       'MediaTek Dimensity 810 Processor',
       'Qualcomm Snapdragon 778G Processor',
       'Qualcomm Snapdragon 695 5G Processor',
       'Qualcomm Snapdragon 7+ Gen 2 (4nm) Processor',
       'MediaTek Helio G35 Processor',
       'Qualcomm Snapdragon 730G Processor', 'MediaTek G35 Processor',
       'Qualcomm Snapdragon 845 Processor',
       'Qualcomm Snapdragon 870 Processor',
       'MediaTek Helio G80 Processor',
       'Qualcomm Snapdragon 720G Processor',
       'Qualcomm Snapdragon 860 Processor',
       'Qualcomm Snapdragon 662 Processor',
       'Qualcomm Snapdragon 732G Processor',
       'MediaTek Dimensity 1200 Processor', 'Helio G88 Processor',
       'Unisoc T612 Processor', 'MediaTek Helio G99 Octa Core Processor',
       'Unisoc T612 processor Processor',
       'MediaTek Dimen

In [34]:
import pandas as pd
import re

def clean_processor(processor):
    processor = processor.lower().strip()
    processor = re.sub(r'[^a-z0-9\s]', '', processor) 
    return processor

def extract_processor_brand(processor):
    if 'mediatek' in processor or 'dimensity' in processor:
        return 'MediaTek'
    elif 'snapdragon' in processor:
        return 'Qualcomm'
    elif 'exynos' in processor:
        return 'Exynos'
    elif 'unisoc' in processor or 'spreadtrum' in processor:
        return 'Unisoc'
    elif 'kirin' in processor:
        return 'Kirin'
    elif 'tensor' in processor:
        return 'Google Tensor'
    elif 'octa core' in processor or 'quad core' in processor:
        return 'Generic (Unbranded)'
    else:
        return 'Qualcomm' 

df['Processor_Cleaned'] = df['Processor'].apply(clean_processor)
df['Processor_Brand'] = df['Processor_Cleaned'].apply(extract_processor_brand)

df = df.drop(columns=['Processor_Cleaned'])

print(df)


                                         Phone Name  RAM  ROM  Back Camera  \
0                     POCO M4 5G (Cool Blue, 64 GB)    4   64           50   
1                       POCO C55 (Cool Blue, 64 GB)    4   64           50   
2                   POCO M4 5G (Power Black, 64 GB)    4   64           50   
3                     POCO C55 (Power Black, 64 GB)    4   64           50   
4                    POCO C55 (Forest Green, 64 GB)    4   64           50   
...                                             ...  ...  ...          ...   
1799              vivo T2x 5G (Aurora Gold, 128 GB)    6  128           50   
1800              vivo T2x 5G (Marine Blue, 128 GB)    6  128           50   
1801  SAMSUNG Galaxy S23 5G (Phantom Black, 128 GB)    8  128           50   
1802             vivo Y28s 5G (Vintage Red, 128 GB)    6  128           50   
1803  SAMSUNG Galaxy S23 5G (Phantom Black, 256 GB)    8  256           50   

      Front_Camera  Battery                              Proces

In [35]:
df['Processor_Brand'].value_counts()

Processor_Brand
Qualcomm               811
MediaTek               801
Exynos                  90
Unisoc                  73
Generic (Unbranded)     12
Google Tensor           11
Kirin                    6
Name: count, dtype: int64

In [44]:
df['Processor_Brand'].unique()
df.drop(columns=['Processor'],inplace=True)

In [45]:
df.head(5)

Phone Name  RAM  ROM  Back Camera  Front_Camera  \
0    POCO M4 5G (Cool Blue, 64 GB)    4   64           50             8   
1      POCO C55 (Cool Blue, 64 GB)    4   64           50             5   
2  POCO M4 5G (Power Black, 64 GB)    4   64           50             8   
3    POCO C55 (Power Black, 64 GB)    4   64           50             5   
4   POCO C55 (Forest Green, 64 GB)    4   64           50             5   

   Battery  Price Processor_Brand  
0     5000  11999        MediaTek  
1     5000   7749        MediaTek  
2     5000  11999        MediaTek  
3     5000   7749        MediaTek  
4     5000   7749        MediaTek

In [46]:
x=df.iloc[:, :-2]
x=pd.concat([x, df.iloc[:, -1]], axis=1)
y=df["Price"]

y.head(5)

0    11999
1     7749
2    11999
3     7749
4     7749
Name: Price, dtype: int64

In [47]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [48]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.pipeline import Pipeline
from sklearn.linear_model import Ridge
from sklearn.metrics import r2_score
step1 = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), ['RAM', 'ROM', 'Back Camera', 'Front_Camera', 'Battery']),
        ('cat', OneHotEncoder(handle_unknown='ignore', sparse_output=False), ['Processor_Brand', 'Phone Name'])  # Use sparse_output=False
    ],
    remainder='passthrough'
)
step2 = Ridge(alpha=0.01)
pipe = Pipeline([
    ('step1', step1),
    ('step2', step2)
])
pipe.fit(x_train, y_train)
y_pred = pipe.predict(x_test)
print(r2_score(y_test, y_pred))


0.7194414863973033


In [51]:
from sklearn.ensemble import StackingRegressor
from sklearn.linear_model import Ridge, LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.svm import SVR
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from xgboost import XGBRegressor
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.pipeline import Pipeline
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error, median_absolute_error
import joblib

base_regressors = [
    ('ridge', Ridge(alpha=0.01)),
    ('lr', LinearRegression()),
    ('dt', DecisionTreeRegressor(random_state=42)),
    ('rf', RandomForestRegressor(random_state=42)),
    ('svr', SVR()),
    ('gbr', GradientBoostingRegressor(random_state=42)),
    ('xgb', XGBRegressor(random_state=42))
]

meta_regressor = LinearRegression()

step1 = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), ['RAM', 'ROM', 'Back Camera', 'Front_Camera', 'Battery']),
        ('cat', OneHotEncoder(handle_unknown='ignore'), ['Processor_Brand', 'Phone Name'])
    ],
    remainder='passthrough'
)

stacking_regressor = StackingRegressor(
    estimators=base_regressors,
    final_estimator=meta_regressor
)

pipe_stacking = Pipeline([
    ('step1', step1),
    ('stacking', stacking_regressor)
])

pipe_stacking.fit(x_train, y_train)
y_pred_stacking = pipe_stacking.predict(x_test)

print("R2 Score for Stacking Regressor:", r2_score(y_test, y_pred_stacking))
print("Mean Absolute Error:", mean_absolute_error(y_test, y_pred_stacking))
print("Mean Squared Error:", mean_squared_error(y_test, y_pred_stacking))
print("Median Absolute Error:", median_absolute_error(y_test, y_pred_stacking))

joblib.dump(pipe_stacking, 'stacking_regressor_model.pkl')


R2 Score for Stacking Regressor: 0.8207861390251353
Mean Absolute Error: 2807.3224735321314
Mean Squared Error: 15541961.76803614
Median Absolute Error: 2036.0762226273946


['stacking_regressor_model.pkl']